name: Tag and Post-Release Action

on:
  push:
    branches:
      - main

  release:
    types: [published]

jobs:
  create-tag:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Read version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=v$VERSION" >> $GITHUB_ENV

      - name: Check if tag already exists
        run: |
          if git rev-parse ${{ env.VERSION }} >/dev/null 2>&1; then
            echo "Tag ${{ env.VERSION }} já existe. Cancelando..."
            exit 0
          fi

      - name: Create and push Git tag
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

  post-release:
    name: Run action after release
    needs: create-tag
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Post-release step
        run: |
          echo "Executando ações pós-release..."
          # Ex: docker build, deploy, etc.
