name: Rollback Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag para remover e fazer rollback"
        required: true

jobs:
  delete-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Git, deletar tag remota e fazer checkout de tag antiga
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} repo
          cd repo

          git push origin --delete refs/tags/${{ github.event.inputs.tag }}
          git checkout tags/${{ github.event.inputs.tag }}
          git checkout -b rollback-${{ github.event.inputs.tag }}
          git push origin rollback-${{ github.event.inputs.tag }}
