name: Rollback Tag

on:
  workflow_dispatch:
    inputs:
      tag_to_delete:
        description: "Tag para remover"
        required: true
      tag_to_checkout:
        description: "Tag para voltar a main (ex: v1.0.0)"
        required: true

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Git, preparar rollback da main
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@users.noreply.github.com"

          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} repo
          cd repo

          # (Opcional) Deleta a tag remota
          # git push origin --delete refs/tags/${{ github.event.inputs.tag_to_delete }}

          # Cria uma branch com o estado atual da main, para backup
          git checkout main
          git checkout -b rollback-${{ github.event.inputs.tag_to_delete }}
          git push origin rollback-${{ github.event.inputs.tag_to_delete }}

          # Reseta main para o commit da tag antiga
          git checkout main
          git reset --hard ${{ github.event.inputs.tag_to_checkout }}
          git push origin main --force

          echo 'Publicando ...'
