name: Rollback Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag para remover"
        required: true

jobs:
  delete-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Git e deletar tag remota
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git clone https://github.com/${{ github.repository }} repo
          cd repo
          git push origin --delete refs/tags/${{ github.event.inputs.tag }}
